version: '3'
services:
    voi-backend:
        command: sh -c "
            sleep 15 &&
            python main.py"
        volumes:
            - voi-production-audio:/audio_data

    voi-postgres:
        volumes:
            - voi-production-pg:/var/lib/postgresql/data

    voi-es:
        volumes:
            - voi-production-es:/usr/share/elasticsearch/data

    voi-kibana:
        image: docker.elastic.co/kibana/kibana:6.6.0
        container_name: voi-kibana
        environment:
            ELASTICSEARCH_URL: http://voi-es:9200
            ELASTICSEARCH_HOSTS: http://voi-es:9200
        ports:
            - 5601:5601
