version: '3'
services:
    voi-backend:
        build: ./FlaskBackend
        container_name: voi-backend
        ports:
            - 80:80
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: voi
            POSTGRES_DB: postgres
            POSTGRES_PORT: 5432
            POSTGRES_HOST: voi-postgres
            ELASTIC_HOST: voi-es
            ELASTIC_PORT: 9200
            PORT: 80
            AUDIO_DIR: /audio_data
            PYTHONUNBUFFERED: 1
        depends_on:
            - voi-postgres
            - voi-es
        links:
            - voi-postgres
            - voi-es

    voi-postgres:
        image: "postgres:9.6-alpine"
        container_name: voi-postgres
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: voi
        ports:
            - 5432:5432

    voi-es:
        image: 'elasticsearch:6.6.0'
        container_name: voi-es
        restart: always
        environment:
            - node.name=voi-es
            - discovery.type=single-node
        ports:
            - 9200:9200


volumes:
    voi-production-pg:
        driver: local
    voi-testing-pg:
        driver: local
    voi-production-audio:
        driver: local
    voi-testing-audio:
        driver: local
    voi-production-es:
        driver: local
    voi-testing-es:
        driver: local
